---
title: "c9w4 Quiz 3"
author: "Robert Handsfield"
date: "11/8/2015"
output: html_document
---


# Question 1

Which of the following items is required for an R package to pass R CMD check without any warnings or errors?

a) vignette
b) a demo directory
c) An explicit software license
d) unit tests


## Solution


## Answer


---

# Question 2

Which of the following is a generic function in a fresh installation of R, with only the default packages loaded?

a) lm  
b) dgamma  
c) __colSums__  
d) predict  

## Solution
Use `r ?base`, then search function names. Or, use `r ?colSums` (and others) to find package for each function.

## Answer
__Answer:__ colSums

---

# Question 3

What function is used to obtain the function body for an S4 method function?

a)getS3method()
b)getClass()
c)getMethod()
d)showMethods()


## Solution


## Answer


---

# Question 4

Which one of the following functions must be defined in order to deploy an R function on yhat?

a)model.load
b)model.transform
c)model.predict
d)model.require


## Solution


## Answer


---

# Question 5

Please download the R package DDPQuiz3 from the course web site. Examine the createmean function implemented in the R/ sub-directory. What is the appropriate text to place above the createmean function for Roxygen2 to create a complete help file?

a)
#' This function calculates the mean  
#'   
#' @param x is a numeric vector  
#' @return the mean of x  
#' @export  
#' @examples   
#' x <- 1:10  
#' createmean(x)  
  
b)  
#' This function calculates the mean  
#'   
#' @param x is a numeric vector  
#' @export  
#' @examples   
#' x <- 1:10  
#' createmean(x)  
  
c)  
#' This function calculates the mean  
#'   
#' @param x is a numeric vector  
#' @return the mean of x  
#' @export  
#' @examples   
#' x <- 1:10  
#' createmean(y)  
  
d)  
#' This function calculates the mean  
#'  
#' @param x is a numeric vector  
#' @return the mean of x  
#' @export  
#' @examples   
#' x <- 1:10  
#' createmean(x)


## Solution


## Answer


