---
title: "c6_swirl"
author: "R. Handsfield"
date: "January 12, 2016"
output: html_document
---

# Swirl Assignments - Statistical Inference

Install the Statistical Inference swirl course
```{r eval=FALSE}
# install
install_from_swirl("Statistical Inference")

# load course
swirl()
```



## Week 1

### Introduction
Username for this session is 'R'.

Which of the following is NOT an example of statistical inference?  
__2: Recording the results of a statistics exam__ involves concrete data that doesn't require any inference or generalization.

Which of the following would NOT be a source of bad data?  
__4: A randomly selected sample of population__

So with statistical inference we use data to draw general conclusions about a population. Which of the following would a scientist using
statistical inference techniques consider a problem?  
__3: Contaminated data__

Which of the following is NOT an example of statistical inference in action?  
__2: Counting sheep__

We want to emphasize a couple of important points here. First, a statistic (singular) is a number computed from a sample of data. We use statistics to infer information about a population. Second, a random variable is an outcome from an experiment. Deterministic processes, such as computing means or variances, applied to random variables, produce additional random variables which have their own distributions. It's important to keep straight which distributions you're talking about.

Finally, there are two broad flavors of inference. The first is __frequency,__ which uses "long run __proportion of times an event occurs__ in independent, identically distributed repetitions." The second is Bayesian in which the __probability estimate__ for a hypothesis __is updated as additional evidence is acquired.__ Both flavors require an understanding of probability so that's what the next lessons will cover.

__Assignment Token:__ 2Fob468GfJv0AfeV

### Probability1

The first step in understanding probability is to see if you understand what outcomes of an experiment are possible. For instance, if you were rolling a single, fair die once, how many outcomes are possible?  
__1: 6__

The probability of a particular outcome of an experiment is the ratio of the number of ways that outcome can occur to all possible outcomes of the experiment. Since there are 6 possible outcomes to the experiment of rolling a die, and we assume the die is fair, each outcome is equally likely. So what is the probability of rolling a 2?  
__3: 1/6__

What is the probability of rolling an even number?  
__4: 1/2__

If A and B are two independent events then the probability of them both occurring is the product of the probabilities. $P(A&B) = P(A) * P(B)$ Suppose you rolled the fair die twice in succession. What is the probability of rolling two 4's?  
__3: 1/36__

Suppose you rolled the fair die twice. What is the probability of rolling the same number two times in a row?  Since we don't care what the outcome of the first roll is, its probability is 1. The second roll of the dice has to match the outcome of the first, so that has a probability of 1/6. The probability of both events occurring is 1 * 1/6.  
__1: 1/6__

Now consider the experiment of rolling 2 dice, one red and one green. Assume the dice are fair and not loaded. How many distinct outcomes are possible?  
__3: 36__

Rolling these two dice, what's the probability of rolling a 10?  
__2: 3/36__

What sum is the most likely when rolling these two dice?  
__3: 7__

The probability of at least one of two events, A and B, occurring is the sum of their individual probabilities minus the probability of their intersection. P(A U B) = P(A) + P(B) - P(A&B). It's easy to see why this is. Calculating P(A) and P(B) counts outcomes that are in both A and B twice, so they're overcounted. The probability of the intersection of the two events, denoted as A&B, must be subtracted from the sum.

Back to rolling two dice. Which expression represents the probability of rolling an even number or a number greater than 8? The probability of rolling an even number is 1/2 or 18/36. There are 10 ways of rolling a number greater than '8' - 4 ways for rolling '9', 3 for '10', 2 for '11' and 1 for '12'. How big is the intersection between rolling an even number and those greater than '8'?

9	4,5 3,6
10	4,6 5,5
11    	5,6
12   	6,6

__4: (18+10-4)/36__

It follows that if A and B are disjoint or mutually exclusive, i.e. only one of them can occur, then P(A U B) = P(A)+P(B).

Which of the following expressions represents the probability of rolling a number greater than 10?  
__2: (2+1)/36__

Use the answer to the previous question and the fact that the sum of all outcomes must sum to 1 to determine the probability of rolling a number less than or equal to 10.  
__33/36__

A deck of cards is a set of 52 cards, 4 suits of 13 cards each. There are two red suits, diamonds and hearts, and two black suits, spades and clubs. Each of the 13 cards in a suit has a value - an ace which is sometimes thought of as 1, a number from 2 to 10, and 3 face cards, king, queen, and jack. We've created a deck in R for you. Type 'deck' to see it now.

When drawing a single card, how many outcomes are possible?  
__52__

What is the probability of drawing a jack?  
__4/52__

If you're dealt a hand of 5 cards, what is the probability of getting all 5 of the same value?  
__0__

What is the probability of drawing a face card?  
__12/52__

Suppose you draw a face card and don't replace it in the deck. What is the probability that when you draw a second card it also will be a face card?  
__1: 11/51__

Suppose you draw a face card and don't replace it in the deck. What is the probability that when you draw a second card it also will be a face card of the same suit?  
__2/51__

__Assignment Token:__ 8VfbrCQNdcQYVALS




### Probability2

### ConditionalProbability

### Expectations




