---
title: "c6w4q1"
author: "R. Handsfield"
date: "January 14, 2016"
output: html_document
---

# 1.
A pharmaceutical company is interested in testing a potential blood pressure lowering medication. Their first examination considers only subjects that received the medication at baseline then two weeks later. The data are as follows (SBP in mmHg)

| Subject | Baseline | Week 2
|---------|----------|-------
| 1	  | 140	     | 132
| 2	  | 138	     | 135
| 3	  | 150	     | 151
| 4	  | 148	     | 146
| 5	  | 135	     | 130

Consider testing the hypothesis that there was a mean reduction in blood pressure? Give the P-value for the associated two sided T test.

(Hint, consider that the observations are paired.)

a) 0.10
b) 0.05
c) 0.087
d) 0.043

## Solution


__Answer: __

# 2.
A sample of 9 men yielded a sample average brain volume of 1,100cc and a standard deviation of 30cc. What is the complete set of values of μ0 that a test of H0:μ=μ0 would fail to reject the null hypothesis in a two sided 5% Students t-test?

a) 1077 to 1123
b) 1081 to 1119
c) 1080 to 1120
d) 1031 to 1169

## Solution


__Answer: __

# 3.
Researchers conducted a blind taste test of Coke versus Pepsi. Each of four people was asked which of two blinded drinks given in random order that they preferred. The data was such that 3 of the 4 people chose Coke. Assuming that this sample is representative, report a P-value for a test of the hypothesis that Coke is preferred to Pepsi using a one sided exact test.

a) 0.10
b) 0.005
c) 0.62
d) 0.31

## Solution

__Answer: __

# 4.
Infection rates at a hospital above 1 infection per 100 person days at risk are believed to be too high and are used as a benchmark. A hospital that had previously been above the benchmark recently had 10 infections over the last 1,787 person days at risk. About what is the one sided P-value for the relevant test of whether the hospital is *below* the standard?

a) 0.52
b) 0.22
c) 0.03
d) 0.11

## Solution

__Answer: __

# 5.
Suppose that 18 obese subjects were randomized, 9 each, to a new diet pill and a placebo. Subjects’ body mass indices (BMIs) were measured at a baseline and again after having received the treatment or placebo for four weeks. The average difference from follow-up to the baseline (followup - baseline) was −3 kg/m2 for the treated group and 1 kg/m2 for the placebo group. The corresponding standard deviations of the differences was 1.5 kg/m2 for the treatment group and 1.8 kg/m2 for the placebo group. Does the change in BMI appear to differ between the treated and placebo groups? Assuming normality of the underlying data and a common population variance, give a pvalue for a two sided t test.

a) Less than 0.05, but larger than 0.01
b) Less than 0.10 but larger than 0.05
c) Larger than 0.10
d) Less than 0.01

## Solution

__Answer: __

# 6
Brain volumes for 9 men yielded a 90% confidence interval of 1,077 cc to 1,123 cc. Would you reject in a two sided 5% hypothesis test of  H0:μ=1,078?

a) No you wouldn't reject.
b) It's impossible to tell.
c) Where does Brian come up with these questions?
d) Yes you would reject.

## Solution

__Answer: __

# 7
Researchers would like to conduct a study of 100 healthy adults to detect a four year mean brain volume loss of .01 mm3. Assume that the standard deviation of four year volume loss in this population is .04 mm3. About what would be the power of the study for a 5% one sided test versus a null hypothesis of no volume loss?

a) 0.80
b) 0.60
c) 0.70
d) 0.50

## Solution

__Answer: __

# 8
Researchers would like to conduct a study of n healthy adults to detect a four year mean brain volume loss of .01 mm3. Assume that the standard deviation of four year volume loss in this population is .04 mm3. About what would be the value of n needed for 90% power of type one error rate of 5% one sided test versus a null hypothesis of no volume loss?

a) 120
b) 180
c) 160
d) 140

## Solution

__Answer: __

# 9
As you increase the type one error rate, α, what happens to power?

a) It's impossible to tell given the information in the problem.
b) You will get larger power.
c) You will get smaller power.
d) No, for real, where does Brian come up with these problems?

## Solution

__Answer: __

